
import streamlit as st
import pandas as pd
import joblib
from pathlib import Path

# --------------------------------------------------
# Page configuration
# --------------------------------------------------
st.set_page_config(
    page_title="Medical Insurance Cost Predictor",
    page_icon="🏥",
    layout="centered"
)


# --------------------------------------------------
# Load saved model and preprocessor
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent


@st.cache_resource
def load_files():
    model = joblib.load(BASE_DIR / "fake_job_detector.pkl")
    preprocessor = joblib.load(BASE_DIR / "preprocessor.pkl")

    return model, preprocessor


model, preprocessor = load_files()


# --------------------------------------------------
# Application heading
# --------------------------------------------------
st.title("🏥 Medical Insurance Cost Predictor")

st.write(
    "Enter the person's details to estimate their medical insurance cost."
)


# --------------------------------------------------
# User inputs
# --------------------------------------------------
age = st.number_input(
    "Age",
    min_value=18,
    max_value=100,
    value=30,
    step=1
)

sex = st.selectbox(
    "Sex",
    options=["female", "male"]
)

bmi = st.number_input(
    "BMI",
    min_value=10.0,
    max_value=60.0,
    value=25.0,
    step=0.1
)

children = st.number_input(
    "Number of Children",
    min_value=0,
    max_value=10,
    value=0,
    step=1
)

smoker = st.selectbox(
    "Smoker",
    options=["no", "yes"]
)

region = st.selectbox(
    "Region",
    options=[
        "northeast",
        "northwest",
        "southeast",
        "southwest"
    ]
)


# --------------------------------------------------
# Prediction
# --------------------------------------------------
if st.button("Predict Insurance Cost", use_container_width=True):

    input_data = pd.DataFrame({
        "age": [age],
        "sex": [sex],
        "bmi": [bmi],
        "children": [children],
        "smoker": [smoker],
        "region": [region]
    })

    processed_input = preprocessor.transform(input_data)

    prediction = model.predict(processed_input)[0]

    st.success(
        f"Estimated Medical Insurance Cost: ${prediction:,.2f}"
    )

    st.caption(
        "This prediction is generated by a machine-learning model "
        "and should not be treated as an actual insurance quotation."
    )
